/**
 * Embedded Menen Verify public key + product plan.
 *
 * The public key is the RSA-2048 public half of the key pair generated by the
 * Menen Verify admin tool (E:\Menen Verify\keys\). Activation codes are RS256
 * JWTs signed with the matching PRIVATE key by the admin tool and verified
 * here completely OFFLINE inside the WebView (WebCrypto) — no network call.
 *
 * Keep in sync with E:\Menen Verify\keys\public.pem. Regenerating the key pair
 * there invalidates every license issued before the change.
 */
export const MENEN_VERIFY_PUBLIC_KEY_PEM = `-----BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAlarpMUU3M55DbaG1tV6P
nNY5tkNdBJPqUgDjh0EEPPJwDMFBKz+BhfXQ/iWzgVNWQE+UmfEwUNpgLbIwtitb
nnj9GihETMFSpspEvjatTaWtS0H3+CgH0B4wjP2NOy1GtltCbaPVjv+8vEHPDLRT
rxcE9YqI80PHpd6Uiz+LeNuQAsNAfxKXsZ7TaCTlQxtPxRk9nBLCDMCzyJFuaHIi
IV3lh51/zUW1niP6NiKA2BFsIKvL/TbybDc8xVOqJa6gF9hXIcKAnSzrf2o9OaLq
sWjJEIjwLNMwShIvnnqQMY6/I64Pbu6F9CryAD+dgd3br8olQ+ub9mzKPtpCKUq2
DwIDAQAB
-----END PUBLIC KEY-----`;

/** Issuer the admin tool signs codes with. Codes from other issuers are rejected. */
export const LICENSE_ISSUER = 'menen-verify';

/** Product sold for this build. The admin must select the matching product when issuing a code. */
export const LICENSE_PRODUCT_ID = 'menen-grade12';

/**
 * Commercial/plan copy shown on the Activation screen. Placeholder values —
 * replace with the real school branch, account and price before launch.
 */
export const LICENSE_PRODUCT_PLAN = {
  productLabel: 'Menen Student Assistant Max',
  price: 'ETB 500 / device / school year',
  payment: {
    bank: 'Bank of Abyssinia',
    branch: 'Sarbet / 6 Kilo (Menen School)',
    accountName: 'Menen School ICT Revenue',
    accountNumber: '1000020001'
  },
  contactNote: 'Send the deposit receipt plus this Device Code to the school administrator; the activation code is returned offline.',
  features: [
    'Full 6,192-question national ESLCE exam bank (2000–2016 E.C.)',
    'Predicted 2026 national exam sets per subject with scaled-score (0–700) evaluation',
    'Unlimited daily practice runs (free plan: 5 runs/day)',
    'Reading passage drills linked to each exam'
  ]
} as const;

/**
 * Grade 9/10/11 APKs contain no ESLCE content (it is a Grade-12-only national
 * qualification), so their premium pitch must not promise it. The free/premium
 * mechanism itself — device code, activation code, isPremium() — is unchanged.
 */
const FEATURES_NO_ESLCE: readonly string[] = [
  'Unlimited timed mock exams for every subject in this grade',
  'Full exam-question bank with worked explanations for every answer',
  'Unlimited daily practice runs (free plan: 5 runs/day)',
  'Detailed progress reports, mastery tracking and revision streaks'
];

export function premiumFeatures(hasEslce: boolean): readonly string[] {
  return hasEslce ? LICENSE_PRODUCT_PLAN.features : FEATURES_NO_ESLCE;
}

/** Free-plan summary shown on the activation and settings screens. */
export function freePlanSummary(hasEslce: boolean): string {
  return hasEslce
    ? 'On the free plan you get 5 ESLCE practice runs a day with past papers only. Activate offline with a code from the school to unlock the full bank.'
    : 'On the free plan you get 5 timed exam runs a day with past papers only. Activate offline with a code from the school to unlock the full bank.';
}